apiVersion: v1
kind: Service
metadata:
  name: mendix-vpa
  labels:
    app: mendix-vpa
spec:
  type: ClusterIP
  selector:
    app: mendix-vpa
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mendix-vpa
  labels:
    app: mendix-vpa
spec:
  selector:
    matchLabels:
      app: mendix-vpa
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mendix-vpa
    spec:
      containers:
      - name: mendix-vpa
        image: aimvector/application-cpu:v1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "2000m"